### ISSUE TITLE
NameError: name 'url' is not defined in update_entity

### ISSUE THREAD

**Issue by fisuda** [smartsdk/entities-simulator#3]
I encountered the following error.

Traceback (most recent call last):
  File "entities_simulator.py", line 90, in <module>
    update_entity(ORION_URL, e, attrs_to_update)
  File "entities_simulator.py", line 52, in update_entity
    r = requests.patch(url,
NameError: name 'url' is not defined

**Comment by taliaga** [comment]
thanks @fisuda !
